[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_programs = "3QrZkcW2REEEjGjzRy8Ccedq8GjQMPkKAoxdbi4nf88n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/storacha-sol.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
